### ISSUE TITLE
Add clarification about s1 argument in importUserJob

### ISSUE THREAD

**Issue by freethejazz** [spring-guides/gs-batch-processing#10]
Looking at the example, I can't figure out how the `importUserJob` can just declare an argument of type Step and know to pull in the value of the `step1` bean. I can only assume it knows to do that because there's only one `Step`-typed bean defined, which leads me to wonder what I'd need to do if I wanted two steps defined for a job, or if I had two jobs defined each with one step.

Do you think it would be valuable to add information about how to ensure steps are going into the right job? I know it's not directly applicable to this example, but it may merit either making the example slightly more complicated to include another step. Alternatively, and a potential better approach, may be to use a way of defining steps for jobs in a less opaque way (directly calling the method, for example). Or maybe keep the example the same but explain what's going on?

I'm far from an expert on this, so there might be something obvious that I'm missing.

**Comment by dsyer** [comment]
I dislike the way this is implemented too, but I assume someone did it on purpose, so I hesitate to change it without asking. Maybe @mminella should have a look (if you're here Michael, would it be OK to convert the Java source to tab indents, like normal Spring code?).

The problem is it's not a trivial change because of the way the dependency injection is organised here. A method call to `step1()` would be entirely appropriate IMO, but the `step1()` method has parameters. The thing to do, to show best practice, would be to move the `@Bean` declarations for the `Item*` dependencies of the step into an inner class (so there is no way for Spring to trip up with bean instantiation ordering) and `@Autowired` them back into the main `BatchConfiguration`, so the steps can be created with a no-arg method call.

**Comment by mminella** [comment]
@dsyer Reviewing this closer, there are a few things I'd propose changes (available in a PR right now for discussion: https://github.com/spring-guides/gs-batch-processing/pull/11):

1.  Reorganize the dependency injection.
2.  Return concrete types instead of interfaces.  I don't know if it's a hard best practice, but it's been my experience that it's better to return concrete types when using java config because it alleviates the risk of proxies not being able to see everything (step scope is a typical place where people get bitten...return ItemReader which doesn't get registered as a stream for example).

With regards to the formatting, I'm not sure if spaces are a requirement for the guides.  @gregturn would have to give it a blessing before I did that.

**Comment by gregturn** [comment]
@mminella Thanks for poking around with this.

1. I'm okay with the edits made to the code.
2. To switch from spaces might be another migration to entertain in the future. The guides's code was written with spaces as a side effect of sagan itself using spaces. I'm not sure we need to dig up that beast right now.
3. Do any of these changes run aground of the prose in the guide? If so, might need to polish up the text itself.

**Comment by mminella** [comment]
@gregturn With regards to number 3, this PR actually makes some of the prose more accurate (the references to the bean definition methods in the text have no parameters which is now true in the code).    

That being said, there is a chunk of text towards the end of the guide that does not make sense for this guide.  The section that describes what `@SpringBootApplication` does and the paragraphs after it (but before *Build an executable JAR*) are all web focused (talking about web.xml's, etc).  We may want to clean that up a bit to be more non-web focused.
